services:
  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - app_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      ENV: prod
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app_network

  airflow-postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app_network

  airflow-init:
    image: finance-airflow:2.9.3-py312
    build:
      context: .
      dockerfile: airflow/Dockerfile
    depends_on:
      - airflow-postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: America/Montreal
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      PYTHONPATH: /opt/project
      AWS_ACCESS_KEY_ID: ${ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ca-central-1
    volumes:
      - ./:/opt/project
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
    networks:
      - app_network
    command: >
      bash -lc "
        airflow db migrate &&
        airflow users create
          --username admin
          --password admin
          --firstname admin
          --lastname admin
          --role Admin
          --email admin@example.com || true
      "

  airflow-webserver:
    image: finance-airflow:2.9.3-py312
    depends_on:
      - airflow-init
      - airflow-postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: America/Montreal
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      PYTHONPATH: /opt/project
      AWS_ACCESS_KEY_ID: ${ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ca-central-1
    volumes:
      - ./:/opt/project
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    networks:
      - app_network
    command: webserver

  airflow-scheduler:
    image: finance-airflow:2.9.3-py312
    depends_on:
      - airflow-init
      - airflow-postgres
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DEFAULT_TIMEZONE: America/Montreal
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      PYTHONPATH: /opt/project
      AWS_ACCESS_KEY_ID: ${ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ca-central-1
    volumes:
      - ./:/opt/project
      - ./airflow/dags:/opt/airflow/dags
      - airflow_logs:/opt/airflow/logs
    networks:
      - app_network
    command: scheduler

networks:
  app_network:
    driver: bridge

volumes:
  airflow_pgdata:
  airflow_logs: